# Generated by Django 4.0.4 on 2022-07-09 06:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('country_name', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('residence_number', models.CharField(blank=True, max_length=150, null=True)),
                ('residence_lane', models.CharField(blank=True, max_length=255, null=True)),
                ('residence_city', models.CharField(blank=True, max_length=255, null=True)),
                ('residence_State', models.CharField(blank=True, max_length=30, null=True)),
                ('residence_locality', models.CharField(blank=True, max_length=80, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
